#!/usr/bin/env bash
#MISE description="Check or format files"

#USAGE flag "--debug" help="emit debug logs"
#USAGE flag "--fix" help="apply fixes"

set -e
source "${MISE_PROJECT_ROOT}/.config/mise/tasks/_scripts/_helpers"

print_header "Formatting files ..."
[[ "${usage_debug:-false}" == "true" ]] && LOG_LEVEL="debug" || LOG_LEVEL="warn"
[[ "${usage_fix:-false}" == "true" ]] && CMD="fmt" || CMD="check"
[[ "${usage_fix:-false}" == "true" ]] && SORT_PKGJSON="" || SORT_PKGJSON="--check"

dprint ${CMD} \
  --config $MISE_PROJECT_ROOT/dprint.json \
  --allow-no-files \
  --log-level ${LOG_LEVEL}

print_header "Sorting package.json files ..."
pnpm dlx sort-package-json ${SORT_PKGJSON} "**/package.json" --ignore "**/node_modules"

print_header "Formatting done"
