// Generated by @ai-plugins/build from vwf/hooks/hooks.yaml.
// Edit the hook there, not this file.

import { execFileSync } from "node:child_process";

const SCRIPT = "%%AI_PLUGINS_ROOT%%/hooks/mempalace-precompact.sh";
const REASON = "The conversation is about to be compacted. Persist what you still hold via the mempalace MCP tools before it is lost.";

export default function (pi) {
  pi.on("session_before_compact", async event => {
    // The script counts stops, so a session id is all it needs — and
    // `stop_hook_active` is what stops a save cycle re-triggering itself.
    const payload = JSON.stringify({
      session_id: event.session_id ?? event.sessionId ?? "",
      stop_hook_active: event.stop_hook_active === true,
    });

    let out = "";
    try {
      out = execFileSync(SCRIPT, [], { input: payload, encoding: "utf8", timeout: 90000 });
    }
    catch {
      // A hook that cannot run must not take the tool call down with it.
      return;
    }

    // Anything on stdout means the script wants a checkpoint. The model
    // is handed the instruction and continues, rather than being stopped.
    if (out.trim() === "" || out.trim() === "{}") {
      return;
    }
    return { continue: true, additionalContext: REASON };
  });
}
