// Generated by @ai-plugins/renderer from vwf/hooks/hooks.yaml.
// Edit the hook there, not this file.

import { execSync } from "node:child_process";

const COMMAND = "command -v rtk >/dev/null 2>&1 && rtk hook claude || true";

export default function (pi) {
  pi.on("tool_call", async event => {
    // Both spellings are accepted so a payload rename upstream degrades
    // to a no-op rather than a crash on every tool call.
    const tool = event.tool ?? event.tool_name;
    if (tool !== "Bash") {
      return;
    }
    const payload = JSON.stringify({
      tool_name: tool,
      tool_input: event.input ?? event.tool_input ?? {},
    });

    try {
      execSync(COMMAND, { input: payload, encoding: "utf8" });
    }
    catch {
      // A hook that cannot run must not take the tool call down with it.
      return;
    }
  });
}
