#!/usr/bin/env bash
#MISE description="Install/upgrade pnpm dependencies"
#MISE hide=true

set -e
source "${MISE_PROJECT_ROOT}/.config/mise/tasks/_scripts/_helpers"

print_header "Installing node modules ..."
pnpm install --aggregate-output --child-concurrency 10 --network-concurrency 10 --recursive
