#!/usr/bin/env bash
#MISE description="Configure Flutter & Dart"
#MISE hide=true

set -e
source "${MISE_PROJECT_ROOT}/.config/mise/tasks/_scripts/_helpers"

print_header "Configuring Flutter ..."
flutter config --disable-analytics
flutter config --enable-web
flutter config --enable-ios
flutter config --enable-android
dart --disable-analytics

if [ "$MISE_ENV" = "dev" ]; then
  print_header "Accepting Android licenses ..."
  yes | flutter doctor --android-licenses || true
fi

print_header "Flutter configured!"
