#!/usr/bin/env bash

#MISE description="Setup AI plugins"
#MISE hide=true

set -e
source "${MISE_PROJECT_ROOT}/.config/mise/tasks/_scripts/_helpers"

print_header "Upgrading AI tools ..."

print_subheader "Adding marketplaces ..."
pnpx @askviraj/ai-plugins --all --platform claude --project typescript --project cicd

print_subheader "Prune plugins ..."
claude plugin autoremove --scope user --yes
