#!/usr/bin/env bash
#MISE description="Delete dist, node_modules, lockfiles and caches"
#MISE hide=true

set -e
source "${MISE_PROJECT_ROOT}/.config/mise/tasks/_scripts/_helpers"

print_header "Deleting dist ..."
find . -type d -name "dist" -exec rm -rf {} + || true

print_header "Deleting node_modules ..."
find . -type d -name ".pnpm" -prune -o -type d -name "node_modules" -exec rm -rf {} + || true

print_header "Deleting lockfiles ..."
find . -type f -name "pnpm-lock.yaml" -exec rm -f {} + || true

print_header "Deleting tsbuildinfo ..."
find . -type f -name "*.tsbuildinfo" -exec rm -f {} + || true

print_header "Pruning pnpm store ..."
pnpm store prune || true
