#!/usr/bin/env bash
# Generated by build/src/targets/cursor.ts — do not edit.
#
# Cursor answers a hook with {permission, user_message, agent_message} and has
# no `updatedInput`, so a rewrite is impossible here. This runs the neutral
# script unchanged and translates its answer: a would-be rewrite becomes a
# denial carrying the correction, so the model reissues the command itself.
set -euo pipefail

payload=$(cat)
answer=$(printf '%s' "$payload" \
  | jq '. + {tool_input: {command: (.command // "")}}' \
  | "$(dirname "$0")/npm-normalize.sh")

if printf '%s' "$answer" | jq -e '.hookSpecificOutput.updatedInput' >/dev/null; then
  jq -n --arg m 'This repo uses pnpm or bun, never npm. Reissue the command with the repo'\''s package manager.' \
    '{permission: "deny", agent_message: $m}'
elif [ "$(printf '%s' "$answer" \
  | jq -r '.hookSpecificOutput.permissionDecision // "allow"')" = "deny" ]; then
  jq -n --arg m "$(printf '%s' "$answer" \
    | jq -r '.hookSpecificOutput.permissionDecisionReason // ""')" \
    '{permission: "deny", agent_message: $m}'
else
  printf '{"permission":"allow"}\n'
fi
