// Generated by @ai-plugins/renderer from typescript/hooks/hooks.yaml.
// Edit the hook there, not this file.

import { execFileSync } from "node:child_process";

const SCRIPT = "%%AI_PLUGINS_ROOT%%/hooks/npm-normalize.sh";
const REASON = "This repo uses pnpm or bun, never npm. Reissue the command with the repo's package manager.";

export default function (pi) {
  pi.on("tool_call", async event => {
    // Both spellings are accepted so a payload rename upstream degrades
    // to a no-op rather than a crash on every tool call.
    const tool = event.tool ?? event.tool_name;
    if (tool !== "Bash") {
      return;
    }
    const payload = JSON.stringify({
      tool_name: tool,
      tool_input: event.input ?? event.tool_input ?? {},
    });

    let out = "";
    try {
      out = execFileSync(SCRIPT, [], { input: payload, encoding: "utf8", timeout: 5000 });
    }
    catch {
      // A hook that cannot run must not take the tool call down with it.
      return;
    }

    // A verdict at all means the script wants this call stopped. Oh-My-Pi
    // cannot apply the fix, so it hands the model the reason instead.
    if (out.trim() === "" || out.trim() === "{}") {
      return;
    }
    return { block: true, reason: REASON };
  });
}
