#!/usr/bin/env bash
#MISE description="Audit pnpm dependencies"
#MISE hide=true

set -e
source "${MISE_PROJECT_ROOT}/.config/mise/tasks/_scripts/_helpers"

print_header "Running pnpm audit ..."
pnpm audit --reporter=summary
