#!/usr/bin/env bash
#MISE description="Upgrade the uv lockfile and re-sync"
#MISE hide=true

set -e
source "${MISE_PROJECT_ROOT}/.config/mise/tasks/_scripts/_helpers"

print_header "Upgrading uv lockfile ..."
uv lock --upgrade
uv sync --all-extras
