#!/usr/bin/env bash
#MISE description="List outdated Flutter packages"
#MISE hide=true

set -e
source "${MISE_PROJECT_ROOT}/.config/mise/tasks/_scripts/_helpers"

print_header "Checking for outdated Flutter packages ..."
flutter pub outdated --no-transitive
